modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TheWandererRaven/RavenCoffeeMod/issues"
[[mods]]
modId="ravencoffee"
version="0.4.0"
displayName="Raven Coffee Mod"
updateJSONURL="https://github.com/TheWandererRaven/RavenCoffeeMod/tree/main#readme"
displayURL="https://github.com/TheWandererRaven/RavenCoffeeMod/tree/main#readme"
logoFile="ravenCoffeeLogo.png"
credits="Credits to me, TheWandererRaven, cheers."
authors="TheWandererRaven"
description='''
I haven't finished this yet! Thanks for downloading tho.
'''
[[dependencies.raven_coffee]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.raven_coffee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.raven_coffee]]
    modId="ravenbrewscore"
    mandatory=true
    versionRange="[1.0.0]"
    ordering="NONE"
    side="BOTH"
