modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://myurl.me/"
[[mods]]
modId="ravencoffee"
version="1.16.3-0.1"
displayName="Raven Coffee Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Credits go for me, TheWandererRaven, cheers."
authors="TheWandererRaven"
description='''
I haven't finished this yet! Thanks for downloading tho.
'''

[[dependencies.raven_coffee]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.raven_coffee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
